CREATE TABLE `user` (
	`USER_ID` INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
    `MBR_NO` VARCHAR(45) NOT NULL,
    `USERNAME` VARCHAR(45) NULL,
    `USER_WEBID` VARCHAR(45) NULL,
    `USER_WEBPW` VARCHAR(45) NULL,
	`CREATE_DATE`	DATETIME	NULL,
	`MODIFY_DATE`	DATETIME	NULL,
	`UNREAD_RECEIPT`	BOOLEAN	NULL,
    `STATUS` BOOLEAN NOT NULL
);

CREATE TABLE `review` (
	`REVIEW_ID` INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
    `USER_ID` INT NOT NULL REFERENCES USER,
	`CREATE_DATE`	DATETIME	NULL,
	`MODIFY_DATE`	DATETIME	NULL,
	`REVIEW_TYPE`	VARCHAR(45)	NULL,
    `DO_DATE` DATE NULL,
    `REVIEW_TITLE` VARCHAR(100) NULL,
    `PUBLISH_DATE` DATE NULL,
    `ABSTRACT_TXT` VARCHAR(300) NULL,
    `PUBLISHER` VARCHAR(45) NULL,
    `DIRECTOR` VARCHAR(45) NULL,
    `PLAYER` VARCHAR(100) NULL,
    `FAVORITE_LINE` VARCHAR(1260) NULL,
    `SHOW_TYPE` VARCHAR(45) NULL,
    `PLACE`  VARCHAR(45) NULL,
    `STATUS` BOOLEAN NOT NULL
);

CREATE TABLE `review_detail` (
	`REVIEW_DETAIL_ID` INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
    `REVIEW_ID` INT NOT NULL REFERENCES REVIEW,
    `DETAIL_REVIEW_TEXT` VARCHAR(3600) NULL,
    `LIST_1_TITLE` VARCHAR(45) NULL,
    `LIST_1_SCORE_TOTAL` INT NULL,
    `LIST_1_SCORE` INT,
    `LIST_1_DESC` VARCHAR(450),
    `LIST_2_TITLE` VARCHAR(45) NULL,
    `LIST_2_SCORE_TOTAL` INT NULL,
    `LIST_2_SCORE` INT,
    `LIST_2_DESC` VARCHAR(450),
    `LIST_3_TITLE` VARCHAR(45) NULL,
    `LIST_3_SCORE_TOTAL` INT NULL,
    `LIST_3_SCORE` INT,
    `LIST_3_DESC` VARCHAR(450),
    `LIST_4_TITLE` VARCHAR(45) NULL,
    `LIST_4_SCORE_TOTAL` INT NULL,
    `LIST_4_SCORE` INT,
    `LIST_4_DESC` VARCHAR(450),
    `LIST_5_TITLE` VARCHAR(45) NULL,
    `LIST_5_SCORE_TOTAL` INT NULL,
    `LIST_5_SCORE` INT,
    `LIST_5_DESC` VARCHAR(450)
);
